// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAg2esrXqGG-_6TkPvpIfc3RlC2xFOysA',
    appId: '1:847296525014:android:ddfd572332cea794',
    messagingSenderId: '847296525014',
    projectId: 'traccar-manager-app',
    databaseURL: 'https://traccar-manager-app.firebaseio.com',
    storageBucket: 'traccar-manager-app.appspot.com',
  );

  /// Muss zu [ios/Runner/GoogleService-Info.plist] und zum Xcode
  /// `PRODUCT_BUNDLE_IDENTIFIER` passen (Zeichen für Zeichen).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL0ACjoJdABA43soyUuxvdLLTYYFpwg1E',
    appId: '1:1029051718031:ios:7c760777d703a01ec753fa',
    messagingSenderId: '1029051718031',
    projectId: 'traccar-41a32',
    storageBucket: 'traccar-41a32.firebasestorage.app',
    iosBundleId: 'de.ednt.AtlasManager',
  );

}